project_id = "odijuvcwgjvevivkxofd"

[functions.setup-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false
